// Localization utilities
export type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja';

export const languages: Record<Language, { name: string; flag: string }> = {
  en: { name: 'English', flag: '🇺🇸' },
  es: { name: 'Español', flag: '🇪🇸' },
  fr: { name: 'Français', flag: '🇫🇷' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  zh: { name: '中文', flag: '🇨🇳' },
  ja: { name: '日本語', flag: '🇯🇵' },
};

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'dealCalculator': 'Deal Calculator',
    'manageScenarios': 'Manage Scenarios',
    'saveScenario': 'Save Scenario',
    'monteCarloResults': 'Monte Carlo Results',

    // Form sections
    'basicInputs': 'Basic Deal Inputs',
    'advancedOptions': 'Advanced Options',
    'advancedStructures': 'Advanced Financial Structures',
    'importData': 'Import Historical Data',

    // Form fields
    'annualRevenue': 'Annual Revenue',
    'churnRate': 'Churn Rate',
    'growthRate': 'Growth Rate',
    'earnOutPercent': 'Earn Out',
    'taxRate': 'Tax Rate',
    'earnOutYears': 'Earn Out Years',
    'sellerFinancingPercent': 'Seller Financing',
    'allCashPercent': 'All Cash',
    'interestRate': 'Interest Rate',
    'inflationRate': 'Inflation Rate',
    'equityStakePercent': 'Equity Stake',
    'warrantPercent': 'Warrant Coverage',
    'preferredReturn': 'Preferred Return',

    // Units
    'percent': '%',
    'currency': 'USD ($)',

    // Actions
    'calculate': 'Calculate',
    'exportPdf': 'Export to PDF',
    'close': 'Close',

    // Messages
    'loading': 'Loading market data and calculating scenarios...',
    'calculationError': 'Calculation Error',
    'tutorialWelcome': 'Welcome to Deal Simulator!',
    'tutorialDesc': 'This tool helps you model different payout structures for business acquisitions.',
    'tutorialSteps': 'Hover over labels for explanations, adjust parameters to compare scenarios, export detailed PDF reports.',
    'getStarted': 'Get Started',
    'chartExportHint': 'Right-click or take screenshot to save chart',
    'csvFormat': 'Upload a CSV file with historical revenue data (columns: year, revenue)',
    'invalidCsv': 'Invalid CSV format. Expected columns: year, revenue',

    // Summary
    'dealSummary': 'Deal Summary',
    'financialMetrics': 'Financial Metrics',
    'industryBenchmarking': 'Industry Benchmarking',
    'total': 'Total',
    'taxes': 'Taxes',
    'net': 'Net',
    'npv': 'NPV',
    'irr': 'IRR',
    'paybackPeriod': 'Payback Period',
    'years': 'years',

    // Industries
    'technology': 'Technology',
    'healthcare': 'Healthcare',
    'financialServices': 'Financial Services',
    'manufacturing': 'Manufacturing',
    'retail': 'Retail',
    'energy': 'Energy',
    'realEstate': 'Real Estate',
    'other': 'Other',
  },
  es: {
    'dealCalculator': 'Calculadora de Acuerdos',
    'manageScenarios': 'Administrar Escenarios',
    'saveScenario': 'Guardar Escenario',
    'monteCarloResults': 'Resultados Monte Carlo',
    'basicInputs': 'Entradas Básicas del Acuerdo',
    'advancedOptions': 'Opciones Avanzadas',
    'advancedStructures': 'Estructuras Financieras Avanzadas',
    'importData': 'Importar Datos Históricos',
    'annualRevenue': 'Ingresos Anuales',
    'churnRate': 'Tasa de Abandono',
    'growthRate': 'Tasa de Crecimiento',
    'earnOutPercent': 'Earn Out',
    'taxRate': 'Tasa de Impuestos',
    'earnOutYears': 'Años de Earn Out',
    'sellerFinancingPercent': 'Financiamiento del Vendedor',
    'allCashPercent': 'Todo en Efectivo',
    'interestRate': 'Tasa de Interés',
    'inflationRate': 'Tasa de Inflación',
    'equityStakePercent': 'Participación en Capital',
    'warrantPercent': 'Cobertura de Warrants',
    'preferredReturn': 'Retorno Preferente',
    'calculate': 'Calcular',
    'exportPdf': 'Exportar a PDF',
    'close': 'Cerrar',
    'loading': 'Cargando datos de mercado y calculando escenarios...',
    'calculationError': 'Error de Cálculo',
    'tutorialWelcome': '¡Bienvenido a Deal Simulator!',
    'tutorialDesc': 'Esta herramienta te ayuda a modelar diferentes estructuras de pago para adquisiciones de empresas.',
    'getStarted': 'Comenzar',
    'chartExportHint': 'Clic derecho o toma captura de pantalla para guardar gráfico',
  },
  fr: {
    'dealCalculator': 'Calculateur d\'Accords',
    'manageScenarios': 'Gérer les Scénarios',
    'saveScenario': 'Sauvegarder le Scénario',
    'monteCarloResults': 'Résultats Monte Carlo',
    'basicInputs': 'Entrées d\'Accord de Base',
    'advancedOptions': 'Options Avancées',
    'advancedStructures': 'Structures Financières Avancées',
    'importData': 'Importer des Données Historiques',
    'annualRevenue': 'Revenus Annuels',
    'churnRate': 'Taux de Désabonnement',
    'growthRate': 'Taux de Croissance',
    'earnOutPercent': 'Earn Out',
    'taxRate': 'Taux d\'Imposition',
    'earnOutYears': 'Années d\'Earn Out',
    'sellerFinancingPercent': 'Financement Vendeur',
    'allCashPercent': 'Tout en Espèces',
    'interestRate': 'Taux d\'Intérêt',
    'inflationRate': 'Taux d\'Inflation',
    'equityStakePercent': 'Participation en Capital',
    'warrantPercent': 'Couverture Warrants',
    'preferredReturn': 'Retour Préférentiel',
    'calculate': 'Calculer',
    'exportPdf': 'Exporter en PDF',
    'close': 'Fermer',
    'loading': 'Chargement des données de marché et calcul des scénarios...',
    'calculationError': 'Erreur de Calcul',
    'tutorialWelcome': 'Bienvenue sur Deal Simulator !',
    'tutorialDesc': 'Cet outil vous aide à modéliser différentes structures de paiement pour les acquisitions d\'entreprises.',
    'getStarted': 'Commencer',
    'chartExportHint': 'Clic droit ou capture d\'écran pour sauvegarder le graphique',
  },
  de: {
    'dealCalculator': 'Deal-Rechner',
    'manageScenarios': 'Szenarien Verwalten',
    'saveScenario': 'Szenario Speichern',
    'monteCarloResults': 'Monte-Carlo-Ergebnisse',
    'basicInputs': 'Grundlegende Deal-Eingaben',
    'advancedOptions': 'Erweiterte Optionen',
    'advancedStructures': 'Erweiterte Finanzstrukturen',
    'importData': 'Historische Daten Importieren',
    'annualRevenue': 'Jahresumsatz',
    'churnRate': 'Abwanderungsrate',
    'growthRate': 'Wachstumsrate',
    'earnOutPercent': 'Earn Out',
    'taxRate': 'Steuersatz',
    'earnOutYears': 'Earn-Out-Jahre',
    'sellerFinancingPercent': 'Verkäuferfinanzierung',
    'allCashPercent': 'Barzahlung',
    'interestRate': 'Zinssatz',
    'inflationRate': 'Inflationsrate',
    'equityStakePercent': 'Kapitalbeteiligung',
    'warrantPercent': 'Warrant-Abdeckung',
    'preferredReturn': 'Bevorzugte Rendite',
    'calculate': 'Berechnen',
    'exportPdf': 'Als PDF Exportieren',
    'close': 'Schließen',
    'loading': 'Marktdaten laden und Szenarien berechnen...',
    'calculationError': 'Berechnungsfehler',
    'tutorialWelcome': 'Willkommen bei Deal Simulator!',
    'tutorialDesc': 'Dieses Tool hilft Ihnen, verschiedene Auszahlungsstrukturen für Unternehmensakquisitionen zu modellieren.',
    'getStarted': 'Loslegen',
    'chartExportHint': 'Rechtsklick oder Screenshot machen, um Diagramm zu speichern',
  },
  zh: {
    'dealCalculator': '交易计算器',
    'manageScenarios': '管理场景',
    'saveScenario': '保存场景',
    'monteCarloResults': '蒙特卡洛结果',
    'basicInputs': '基本交易输入',
    'advancedOptions': '高级选项',
    'advancedStructures': '高级金融结构',
    'importData': '导入历史数据',
    'annualRevenue': '年收入',
    'churnRate': '流失率',
    'growthRate': '增长率',
    'earnOutPercent': '收益分成',
    'taxRate': '税率',
    'earnOutYears': '收益分成年限',
    'sellerFinancingPercent': '卖家融资',
    'allCashPercent': '全现金',
    'interestRate': '利率',
    'inflationRate': '通胀率',
    'equityStakePercent': '股权份额',
    'warrantPercent': '认股权证覆盖',
    'preferredReturn': '优先回报',
    'calculate': '计算',
    'exportPdf': '导出为PDF',
    'close': '关闭',
    'loading': '正在加载市场数据并计算场景...',
    'calculationError': '计算错误',
    'tutorialWelcome': '欢迎使用交易模拟器！',
    'tutorialDesc': '此工具帮助您为企业收购建模不同的支付结构。',
    'getStarted': '开始使用',
    'chartExportHint': '右键点击或截图保存图表',
  },
  ja: {
    'dealCalculator': '取引計算機',
    'manageScenarios': 'シナリオ管理',
    'saveScenario': 'シナリオ保存',
    'monteCarloResults': 'モンテカルロ結果',
    'basicInputs': '基本取引入力',
    'advancedOptions': '詳細オプション',
    'advancedStructures': '高度な金融構造',
    'importData': '履歴データのインポート',
    'annualRevenue': '年間売上',
    'churnRate': '解約率',
    'growthRate': '成長率',
    'earnOutPercent': 'アーンアウト',
    'taxRate': '税率',
    'earnOutYears': 'アーンアウト年数',
    'sellerFinancingPercent': '売り手融資',
    'allCashPercent': '全現金',
    'interestRate': '金利',
    'inflationRate': 'インフレ率',
    'equityStakePercent': '株式持分',
    'warrantPercent': 'ワラントカバレッジ',
    'preferredReturn': '優先リターン',
    'calculate': '計算',
    'exportPdf': 'PDFにエクスポート',
    'close': '閉じる',
    'loading': '市場データを読み込み、シナリオを計算しています...',
    'calculationError': '計算エラー',
    'tutorialWelcome': '取引シミュレーターへようこそ！',
    'tutorialDesc': 'このツールは、企業買収のためのさまざまな支払い構造のモデリングを支援します。',
    'getStarted': '開始',
    'chartExportHint': '右クリックまたはスクリーンショットでチャートを保存',
  },
};

export function t(key: string, language: Language = 'en'): string {
  return translations[language]?.[key] || translations.en[key] || key;
}

export function getCurrencySymbol(currency: string): string {
  const symbols: Record<string, string> = {
    USD: '$',
    EUR: '€',
    GBP: '£',
    JPY: '¥',
    CAD: 'C$',
    AUD: 'A$',
  };
  return symbols[currency] || '$';
}